"""Add consultant_id to appointments

Revision ID: 58a48d2508ff
Revises: 
Create Date: 2025-03-26 02:42:19.453440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58a48d2508ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'consultants', ['consultant_id'], ['id'])
        batch_op.drop_column('consultant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultant', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('consultant_id')

    # ### end Alembic commands ###
